const express = require('express');
const fs = require('fs');
const path = require('path');
const { pool } = require('../db/pool');
const { authenticate, requireRole } = require('../middleware/auth');
const { runBackup, getSettings, rescheduleBackups, BACKUP_DIR } = require('../services/backup');

const router = express.Router();
router.use(authenticate);
router.use(requireRole('admin'));

// A backup filename is always generated by the server itself (see services/backup.js),
// never taken verbatim from a client — this pattern is the allowlist for download/delete.
const SAFE_FILENAME = /^erp-meeting-tracker-\d{8}-\d{6}\.sql$/;

router.get('/settings', async (req, res, next) => {
  try {
    res.json(await getSettings());
  } catch (e) { next(e); }
});

router.put('/settings', async (req, res, next) => {
  try {
    const { enabled, hour, minute } = req.body;
    const h = Number(hour), m = Number(minute);
    if (!Number.isInteger(h) || h < 0 || h > 23) return res.status(400).json({ message: 'Hour must be 0-23' });
    if (!Number.isInteger(m) || m < 0 || m > 59) return res.status(400).json({ message: 'Minute must be 0-59' });

    const current = await getSettings();
    if (current.id) {
      await pool.execute(
        'UPDATE backup_settings SET enabled = ?, hour = ?, minute = ?, updated_by = ? WHERE id = ?',
        [enabled ? 1 : 0, h, m, req.user.id, current.id]
      );
    } else {
      await pool.execute(
        'INSERT INTO backup_settings (enabled, hour, minute, updated_by) VALUES (?, ?, ?, ?)',
        [enabled ? 1 : 0, h, m, req.user.id]
      );
    }

    await rescheduleBackups();
    res.json(await getSettings());
  } catch (e) { next(e); }
});

router.post('/run-now', async (req, res, next) => {
  try {
    const result = await runBackup('manual');
    if (!result.success) return res.status(500).json({ message: result.message });
    res.json({ message: 'Backup completed', ...result });
  } catch (e) { next(e); }
});

router.get('/history', async (req, res, next) => {
  try {
    const [rows] = await pool.query(
      'SELECT * FROM backup_runs WHERE is_deleted = 0 ORDER BY started_at DESC LIMIT 100'
    );
    res.json(rows);
  } catch (e) { next(e); }
});

router.get('/download/:filename', (req, res) => {
  const { filename } = req.params;
  if (!SAFE_FILENAME.test(filename)) return res.status(400).json({ message: 'Invalid filename' });
  const filepath = path.join(BACKUP_DIR, filename);
  if (!fs.existsSync(filepath)) return res.status(404).json({ message: 'Backup file not found' });
  res.download(filepath, filename);
});

router.delete('/:filename', async (req, res, next) => {
  try {
    const { filename } = req.params;
    if (!SAFE_FILENAME.test(filename)) return res.status(400).json({ message: 'Invalid filename' });
    const filepath = path.join(BACKUP_DIR, filename);
    fs.rm(filepath, { force: true }, () => {});
    await pool.execute('UPDATE backup_runs SET is_deleted = 1 WHERE filename = ?', [filename]);
    res.json({ message: 'Backup file removed' });
  } catch (e) { next(e); }
});

module.exports = router;
